import BlackWidow from '../assets/black-widow.png'
import Spider from '../assets/poster-spider.png'
import Tennet from '../assets/tenet.png'
import Withces from '../assets/withces.png'
export const movieList = [
  {
    id: 1,
    title: 'Black Widow',
    poster_url: BlackWidow,
    genres: ['Action', 'Adventure'],
    release_date: 'December 2023',
    is_recommended: false,
  },
  {
    id: 2,
    title: 'The Witches',
    poster_url: Withces,
    genres: ['Action', 'Adventure'],
    release_date: 'January 2024',
    is_recommended: true,
  },
  {
    id: 3,
    title: 'Tennet',
    poster_url: Tennet,
    genres: ['Action', 'Adventure'],
    release_date: 'June 2024',
    is_recommended: false,
  },
  {
    id: 4,
    title: 'Spiderman',
    poster_url: Spider,
    genres: ['Action', 'Adventure'],
    release_date: 'March 2024',
    is_recommended: true,
  },
  {
    id: 5,
    title: 'Black Widow',
    poster_url: BlackWidow,
    genres: ['Action', 'Adventure'],
    release_date: 'December 2023',
    is_recommended: false,
  },
  {
    id: 6,
    title: 'The Witches',
    poster_url: Withces,
    genres: ['Action', 'Adventure'],
    release_date: 'January 2024',
  },
  {
    id: 7,
    title: 'Tennet',
    poster_url: Tennet,
    genres: ['Action', 'Adventure'],
    release_date: 'June 2024',
    is_recommended: false,
  },
  {
    id: 8,
    title: 'Spiderman',
    poster_url: Spider,
    genres: ['Action', 'Adventure'],
    release_date: 'March 2024',
    is_recommended: true,
  },
  {
    id: 9,
    title: 'Black Widow',
    poster_url: BlackWidow,
    genres: ['Action', 'Adventure'],
    release_date: 'December 2023',
    is_recommended: false,
  },
  {
    id: 10,
    title: 'The Witches',
    poster_url: Withces,
    genres: ['Action', 'Adventure'],
    release_date: 'January 2024',
    is_recommended: true,
  },
  {
    id: 11,
    title: 'Tennet',
    poster_url: Tennet,
    genres: ['Action', 'Adventure'],
    release_date: 'June 2024',
    is_recommended: false,
  },
  {
    id: 12,
    title: 'Spiderman',
    poster_url: Spider,
    genres: ['Action', 'Adventure'],
    release_date: 'March 2024',
    is_recommended: false,
  },
  {
    id: 13,
    title: 'Black Widow',
    poster_url: BlackWidow,
    genres: ['Action', 'Adventure'],
    release_date: 'December 2023',
    is_recommended: true,
  },
  {
    id: 14,
    title: 'The Witches',
    poster_url: Withces,
    genres: ['Action', 'Adventure'],
    release_date: 'January 2024',
    is_recommended: false,
  },
  {
    id: 15,
    title: 'Tennet',
    poster_url: Tennet,
    genres: ['Action', 'Adventure'],
    release_date: 'June 2024',
    is_recommended: true,
  },
  {
    id: 16,
    title: 'Spiderman',
    poster_url: Spider,
    genres: ['Action', 'Adventure'],
    release_date: 'March 2024',
    is_recommended: false,
  },
  {
    id: 17,
    title: 'Black Widow',
    poster_url: BlackWidow,
    genres: ['Action', 'Adventure'],
    release_date: 'December 2023',
    is_recommended: true,
  },
  {
    id: 18,
    title: 'The Witches',
    poster_url: Withces,
    genres: ['Action', 'Adventure'],
    release_date: 'January 2024',
    is_recommended: false,
  },
  {
    id: 19,
    title: 'Tennet',
    poster_url: Tennet,
    genres: ['Action', 'Adventure'],
    release_date: 'June 2024',
    is_recommended: true,
  },
  {
    id: 20,
    title: 'Spiderman',
    poster_url: Spider,
    genres: ['Action', 'Adventure'],
    release_date: 'March 2024',
    is_recommended: false,
  },
]
