import BlackWidow from '../assets/black-widow.png'
import Spider from '../assets/poster-spider.png'
import Tennet from '../assets/tenet.png'
import Withces from '../assets/withces.png'
export const movieDummy = [
  {
    id: 1,
    title: 'Black Widow',
    poster_url: BlackWidow,
    genres: ['Action', 'Adventure'],
    release_date: '12 December 2023',
    is_recommended: false,
    duration: '2 Hours 15 Minutes',
  },
  {
    id: 2,
    title: 'The Witches',
    poster_url: Withces,
    genres: ['Action', 'Adventure'],
    release_date: '12 January 2024',
    is_recommended: true,
    duration: '2 Hours 15 Minutes',
  },
  {
    id: 3,
    title: 'Tennet',
    poster_url: Tennet,
    genres: ['Action', 'Adventure'],
    release_date: '12 June 2024',
    is_recommended: false,
    duration: '2 Hours 15 Minutes',
  },
  {
    id: 4,
    title: 'Spiderman',
    poster_url: Spider,
    genres: ['Action', 'Adventure'],
    release_date: '12 March 2024',
    is_recommended: true,
    duration: '2 Hours 15 Minutes',
  },
  // {
  //   id: 5,
  //   title: 'Black Widow',
  //   poster_url: BlackWidow,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 December 2023',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 6,
  //   title: 'The Witches',
  //   poster_url: Withces,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 December 2023',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 7,
  //   title: 'Tennet',
  //   poster_url: Tennet,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 June 2024',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 8,
  //   title: 'Spiderman',
  //   poster_url: Spider,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 March 2024',
  //   is_recommended: true,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 9,
  //   title: 'Black Widow',
  //   poster_url: BlackWidow,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 December 2023',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 10,
  //   title: 'The Witches',
  //   poster_url: Withces,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 January 2024',
  //   is_recommended: true,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 11,
  //   title: 'Tennet',
  //   poster_url: Tennet,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 June 2024',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 12,
  //   title: 'Spiderman',
  //   poster_url: Spider,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 March 2024',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 13,
  //   title: 'Black Widow',
  //   poster_url: BlackWidow,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 December 2023',
  //   is_recommended: true,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 14,
  //   title: 'The Witches',
  //   poster_url: Withces,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 January 2024',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 15,
  //   title: 'Tennet',
  //   poster_url: Tennet,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 June 2024',
  //   is_recommended: true,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 16,
  //   title: 'Spiderman',
  //   poster_url: Spider,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 March 2024',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 17,
  //   title: 'Black Widow',
  //   poster_url: BlackWidow,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 December 2023',
  //   is_recommended: true,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 18,
  //   title: 'The Witches',
  //   poster_url: Withces,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 January 2024',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 19,
  //   title: 'Tennet',
  //   poster_url: Tennet,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 June 2024',
  //   is_recommended: true,
  //   duration: '2 Hours 15 Minutes',
  // },
  // {
  //   id: 20,
  //   title: 'Spiderman',
  //   poster_url: Spider,
  //   genres: ['Action', 'Adventure'],
  //   release_date: '12 March 2024',
  //   is_recommended: false,
  //   duration: '2 Hours 15 Minutes',
  // },
]
